import { FormEvent, useEffect, useState } from 'react'
import { api } from '../../lib/api'
import { useAuthStore } from '../../stores/auth.store'
import type { RegistrationForm } from '../../types/portal'

export default function FormsPage() {
  const token = useAuthStore((state) => state.token); const user = useAuthStore((state) => state.user); const [forms,setForms]=useState<RegistrationForm[]>([]); const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [error,setError]=useState('')
  const load=()=>{ if(token) api.forms.list(token).then(setForms).catch(()=>setError('Daftar form tidak dapat dimuat.')) }; useEffect(load,[token])
  const create=async(e:FormEvent)=>{e.preventDefault();if(!token)return;try{await api.forms.create(token,{title,description});setTitle('');setDescription('');load()}catch{setError('Form tidak dapat dibuat. Pastikan akun memiliki akses admin distrik.')}}
  const changeStatus=async(id:string,status:'ACTIVE'|'CLOSED')=>{if(!token)return;try{await api.forms.setStatus(token,id,status);load()}catch{setError('Status form tidak dapat diubah. Pastikan hanya ada satu form aktif.')}}
  const canManage=user?.roles.some((r)=>r.role==='DISTRICT_ADMIN')
  return <div className="px-4 py-8 sm:px-6 lg:px-8"><div className="mb-8"><h1 className="text-2xl font-bold text-gray-800 dark:text-gray-100">Publikasikan Form</h1><p className="mt-2 text-sm text-gray-500">Kelola form pendaftaran pemain untuk workspace ini.</p></div>{canManage&&<form onSubmit={create} className="mb-6 rounded-xl bg-white p-5 shadow-xs dark:bg-gray-800"><div className="grid gap-4 sm:grid-cols-[1fr_1fr_auto]"><input className="form-input" placeholder="Judul form" value={title} onChange={(e)=>setTitle(e.target.value)} required/><input className="form-input" placeholder="Deskripsi (opsional)" value={description} onChange={(e)=>setDescription(e.target.value)}/><button className="btn bg-gray-900 text-gray-100 hover:bg-gray-800" type="submit">Buat Form</button></div></form>} {error&&<p className="mb-5 text-sm text-red-600" role="alert">{error}</p>}<div className="space-y-4">{forms.length===0?<div className="rounded-xl bg-white p-8 text-center text-sm text-gray-500 shadow-xs">Belum ada form pendaftaran.</div>:forms.map((form)=><article key={form.id} className="rounded-xl bg-white p-5 shadow-xs dark:bg-gray-800"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="font-semibold text-gray-800 dark:text-gray-100">{form.title}</h2><p className="mt-1 text-sm text-gray-500">{form.description||'Tidak ada deskripsi'} · {form._count?.submissions??0} pengajuan</p><p className="mt-2 font-mono text-xs text-gray-400">{form.publicToken}</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-violet-500/10 px-2.5 py-1 text-xs font-medium text-violet-700">{form.status==='ACTIVE'?'Aktif':form.status==='CLOSED'?'Ditutup':'Draf'}</span>{canManage&&<button className="text-sm font-medium text-violet-600" onClick={()=>changeStatus(form.id,form.status==='ACTIVE'?'CLOSED':'ACTIVE')}>{form.status==='ACTIVE'?'Tutup Form':'Publikasikan'}</button>}</div></div></article>)}</div></div>
}
