import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api, ApiError } from '../lib/api'
import { useAuthStore } from '../stores/auth.store'
import { useWorkspaceStore } from '../stores/workspace.store'
import type { District } from '../types/auth'

export default function WorkspaceChooser() {
  const navigate = useNavigate(); const user = useAuthStore((state) => state.user); const selectedWorkspace = useWorkspaceStore((state) => state.selectedWorkspace); const selectWorkspace = useWorkspaceStore((state) => state.selectWorkspace); const [districts,setDistricts]=useState<District[]>([]); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const isCentral=user?.roles.some((role)=>role.role==='CENTRAL_ADMIN')??false; const assignedDistrictId=user?.roles.find((role)=>role.role==='DISTRICT_ADMIN')?.districtId
  useEffect(()=>{let active=true;api.districts.list().then((items)=>{if(!active)return;setDistricts(items);if(!isCentral&&assignedDistrictId){const assigned=items.find((district)=>district.id===assignedDistrictId);if(assigned)selectWorkspace(assigned)}}).catch((reason)=>{if(active)setError(reason instanceof ApiError?'Kabupaten/Kota tidak dapat dimuat.':'Terjadi kesalahan saat memuat workspace.')}).finally(()=>active&&setLoading(false));return()=>{active=false}},[assignedDistrictId,isCentral,selectWorkspace])
  const visibleDistricts=useMemo(()=>districts.filter((district)=>`${district.name} ${district.code}`.toLowerCase().includes(query.toLowerCase())),[districts,query])
  if(!isCentral&&assignedDistrictId&&selectedWorkspace)return <main className="min-h-screen bg-white px-4 py-8 font-inter dark:bg-gray-900 sm:px-6 lg:px-8"><div className="mx-auto flex min-h-[70vh] w-full max-w-9xl items-center justify-center"><div className="w-full max-w-md rounded-xl bg-white p-8 text-center shadow-xs dark:bg-gray-800"><p className="text-sm text-gray-500">Workspace Anda</p><h1 className="mt-2 text-2xl font-bold text-gray-800 dark:text-gray-100">{selectedWorkspace.name}</h1><p className="mt-2 text-sm text-gray-500">Workspace distrik siap dibuka.</p><button className="btn mt-6 bg-gray-900 text-gray-100 hover:bg-gray-800" onClick={()=>navigate('/dashboard',{replace:true})}>Buka Workspace</button></div></div></main>
  return <main className="min-h-screen bg-white px-4 py-8 font-inter dark:bg-gray-900 sm:px-6 lg:px-8"><div className="mx-auto w-full max-w-9xl"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-gray-500">PELTI Bali One</p><h1 className="mt-1 text-2xl font-bold text-gray-800 dark:text-gray-100 md:text-3xl">Pilih Workspace</h1><p className="mt-2 text-sm text-gray-500">Pilih Kabupaten/Kota untuk membuka konteks kerja.</p></div><span className="inline-flex w-fit rounded-full bg-violet-500/10 px-3 py-1 text-xs font-medium text-violet-700">Central Admin</span></div>{error&&<div className="mb-6 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700" role="alert">{error}<button className="ml-3 font-semibold underline" onClick={()=>window.location.reload()}>Coba lagi</button></div>}{loading?<div className="rounded-xl bg-white p-8 text-center text-sm text-gray-500 shadow-xs dark:bg-gray-800">Memuat daftar Kabupaten/Kota…</div>:visibleDistricts.length===0?<div className="rounded-xl bg-white p-8 text-center text-sm text-gray-500 shadow-xs dark:bg-gray-800">Tidak ada Kabupaten/Kota.</div>:<><div className="mb-6 max-w-sm"><label className="sr-only" htmlFor="district-search">Cari Kabupaten/Kota</label><input id="district-search" className="form-input w-full" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Cari Kabupaten/Kota…" /></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{visibleDistricts.map((district)=>{const selected=selectedWorkspace?.id===district.id;return <button key={district.id} className={`rounded-xl border bg-white p-5 text-left shadow-xs transition hover:border-violet-300 hover:shadow-sm focus:outline-none focus:ring-2 focus:ring-violet-500/30 dark:bg-gray-800 ${selected?'border-violet-500 ring-1 ring-violet-500':'border-gray-200 dark:border-gray-700/60'}`} onClick={()=>selectWorkspace(district)}><div className="flex items-start justify-between"><div><p className="font-semibold text-gray-800 dark:text-gray-100">{district.name}</p><p className="mt-1 text-xs uppercase tracking-wide text-gray-400">{district.code}</p></div><span className={`mt-1 h-2 w-2 rounded-full ${selected?'bg-violet-500':'bg-gray-200'}`} aria-hidden="true" /></div><p className="mt-5 text-xs text-gray-500">{district._count?.players??0} pemain terdaftar</p></button>})}</div><div className="mt-8 flex justify-end"><button className="btn bg-gray-900 text-gray-100 hover:bg-gray-800 disabled:cursor-not-allowed disabled:opacity-50" disabled={!selectedWorkspace} onClick={()=>navigate('/dashboard',{replace:true})}>Lanjutkan <span className="ml-2">→</span></button></div></>}</div></main>
}
